submission/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'ballot'
urlpatterns = [
    path('ballot/<str:encrypted_pk>',
         views.BallotUpdateView.as_view(),
         name='ballot'),
    path('captains_meeting/<str:encrypted_pk>',
         views.CaptainsMeetingUpdateView.as_view(),
         name='captains_meeting'),

    path('paradigm/<str:judge>',
         views.edit_paradigm,
         name='paradigm'),
    
    path('spirit/<int:team_pk>', 
         views.edit_spirit, 
         name='spirit')
]

tabeasy/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include, path
from ajax_select import urls as ajax_select_urls

from tourney import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('accounts/', include('accounts.urls')),
    path('', include('tourney.urls')),
    path('submission/', include('submission.urls', namespace='submission')),
    path('generate_passwords', views.generate_passwords, name='generate_passwords'),
    path('load_teams', views.load_teams, name='load_teams'),
    path('load_judges', views.load_judges, name='load_judges'),
    path('load_teams_and_judges', views.load_teams_and_judges, name='load_teams_and_judges'),
    path('load_sections', views.load_sections, name='load_sections'),
    path('load_amta_witnesses', views.load_amta_witnesses),
    path('load_paradigms', views.load_paradigms),
    path('donate', views.donate, name='donate'),
    url(r'^ajax_select/', include(ajax_select_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tourney/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'tourney'
urlpatterns = [

    path('refresh', views.refresh, name='refresh'),
    path('edit_characters', views.edit_characters, name='edit_characters'),
    path('pairing', views.pairing_index, name='pairing_index'),
    path('pairing/<int:pk>', views.view_pairing, name='view_pairing'),
    path('pairing/edit/<int:round_num>', views.edit_pairing, name='edit_pairing'),
    path('pairing/delete/<int:round_num>', views.delete_pairing, name='delete_pairing'),
    path('pairing/next_pairing/<int:round_num>', views.next_pairing, name='next_pairing'),
    path('checkin_judges/<int:round_num>', views.checkin_judges, name='checkin_judges'),
    path('clear_checkin/', views.clear_checkin, name='clear_checkin'),
    path('checkin_all_judges/<int:round_num>', views.checkin_all_judges, name='checkin_all_judges'),
    path('view_ballot_status/<int:pairing_id>', views.view_ballot_status, name='view_ballot_status'),
    path('view_spirit_status', views.view_spirit_status, name='view_spirit_status'),
    path('add_spirit_forms', views.add_spirit_forms, name='add_spirit_forms'),
    path('tournament_setting', views.TournamentUpdateView.as_view(),  name='tournament_setting'),
    path('team', views.view_teams, name='view_teams'),
    path('team/<int:pk>', views.view_individual_team, name='view_individual_team'),
    path('team/delete/<int:pk>', views.delete_individual_team, name='delete_individual_team'),
    path('captains_meeting/<int:pairing_id>',
         views.view_captains_meeting_status, name='view_captains_meeting_status'),
    path('results', views.results, name='results'),
    path('individual_awards', views.individual_awards, name='individual_awards'),
    path('team/edit_competitor_pronouns/',
         views.edit_competitor_pronouns,
         name='edit_competitor_pronouns'),
    path('judge', views.view_judges, name='view_judges'),
    path('judge/delete/<int:pk>', views.delete_individual_judge, name='delete_individual_judge'),
    path('judge/<int:pk>', views.view_individual_judge, name='view_individual_judge'),
    path('judge/update_conflict',
         views.ConflictUpdateView.as_view(),
         name='update_conflict'),
    path('judge/judge_friends',
         views.JudgeFriendUpdateView.as_view(),
         name='judge_friend'),
    path('judge/judge_preference',
         views.JudgePreferenceUpdateView.as_view(),
         name='edit_preference'),
    

]

submission/models/ballot.py
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django_better_admin_arrayfield.models.fields import ArrayField

from tourney.models.judge import Judge
from tourney.models.round import Round
from tourney.models.team import Team
from tourney.models.competitor import Competitor
import uuid


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return "ballot_{0}/{1}".format(instance.id, filename)


class Ballot(models.Model):
    round = models.ForeignKey(Round, on_delete=models.CASCADE,
                              related_name='ballots',
                              related_query_name='ballot')
    judge = models.ForeignKey(Judge, on_delete=models.CASCADE,
                              related_name='ballots',
                              related_query_name='ballot')

    att_rank_1 = models.ForeignKey(Competitor, on_delete=models.SET_NULL, related_query_name='att_rank_1',
                                   related_name='att_rank_1', null=True)
    att_rank_2 = models.ForeignKey(Competitor, on_delete=models.SET_NULL, related_query_name='att_rank_2',
                                   related_name='att_rank_2', null=True)
    att_rank_3 = models.ForeignKey(Competitor, on_delete=models.SET_NULL, related_query_name='att_rank_3',
                                   related_name='att_rank_3', null=True)
    att_rank_4 = models.ForeignKey(Competitor, on_delete=models.SET_NULL, related_query_name='att_rank_4',
                                   related_name='att_rank_4', null=True)

    wit_rank_1 = models.ForeignKey(Competitor, on_delete=models.SET_NULL, related_query_name='wit_rank_1',
                                   related_name='wit_rank_1', null=True)
    wit_rank_2 = models.ForeignKey(Competitor, on_delete=models.SET_NULL, related_query_name='wit_rank_2',
                                   related_name='wit_rank_2', null=True)
    wit_rank_3 = models.ForeignKey(Competitor, on_delete=models.SET_NULL, related_query_name='wit_rank_3',
                                   related_name='wit_rank_3', null=True)
    wit_rank_4 = models.ForeignKey(Competitor, on_delete=models.SET_NULL, related_query_name='wit_rank_4',
                                   related_name='wit_rank_4', null=True)
    upload = models.FileField(upload_to=user_directory_path, null=True, blank=True)
    submit = models.BooleanField(default=False, help_text='Submit')

    def att_ranks(self):
        return [self.att_rank_1, self.att_rank_2, self.att_rank_3, self.att_rank_4]

    def wit_ranks(self):
        return [self.wit_rank_1, self.wit_rank_2, self.wit_rank_3, self.wit_rank_4]

    def __str__(self):
        return f"Round {self.round.pairing.round_num} {self.judge}"

    def p_total_score(self):
        p_total_score = 0
        scores = [ballot_section.score for ballot_section in self.sections.filter(
            subsection__side='P').all()]
        for score in scores:
            if score:
                p_total_score += score
        return p_total_score

    def d_total_score(self):
        d_total_score = 0
        scores = [ballot_section.score for ballot_section in self.sections.filter(
            subsection__side='D').all()]
        for score in scores:
            if score:
                d_total_score += score
        return d_total_score

    def calculate_win(self):
        if self.submit:
            return self.p_total_score() - self.d_total_score()
        else:
            return 0

    @property
    def p_result(self):
        if self.submit:
            pd = self.calculate_win()
            if pd != 0:
                return int(pd > 0), pd
            else:
                return 0.5, pd
        else:
            return 0, 0

    @property
    def p_pd(self):
        return self.p_result[1]

    @property
    def p_ballot(self):
        return self.p_result[0]

    @property
    def d_result(self):
        if self.submit:
            pd = self.calculate_win()
            if pd != 0:
                return int(pd < 0), -pd
            else:
                return 0.5, -pd
        else:
            return 0, 0

    @property
    def d_pd(self):
        return self.d_result[1]

    @property
    def d_ballot(self):
        return self.d_result[0]

    class Meta:
        unique_together = ['round', 'judge']

    def clean(self):
        super().clean()
        errors = []
        if not self.round.pairing.round_num == 5 and self.submit:
            if len(self.att_ranks()) != len(set(self.att_ranks())):
                errors.append('You can only rank each attorney once')
            if len(self.wit_ranks()) != len(set(self.wit_ranks())):
                errors.append('You can only rank each witness once')

        if errors != []:
            raise ValidationError(errors)

        self.round.p_team.calc_p_ballots()
        self.round.p_team.calc_d_ballots()
        self.round.p_team.calc_total_ballots()
        self.round.d_team.calc_p_ballots()
        self.round.d_team.calc_d_ballots()
        self.round.d_team.calc_total_ballots()

        self.round.p_team.calc_total_cs()
        self.round.p_team.calc_total_pd()
        self.round.d_team.calc_total_cs()
        self.round.d_team.calc_total_pd()

        for att in [self.att_rank_1, self.att_rank_2, self.att_rank_3, self.att_rank_4]:
            if att:
                att.calc_att_individual_score()

        for wit in [self.wit_rank_1, self.wit_rank_2, self.wit_rank_3, self.wit_rank_4]:
            if wit:
                wit.calc_wit_individual_score()

submission/models/paradigm.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from array_field_select.fields import ArrayField

experience_description_choices = [
    ('hs', 'I am a former high school mock trial competitor.'),
    ('college', 'I am a current or former college mock trial competitor.'),
    ('ls', 'I am a current or former law school mock trial Competitor.'),
    ('judged', 'I have judged 1-2 mock trial competitions in the past.'),
    ('judged_some', 'I have judged 3-5 mock trial competitions in the past.'),
    ('judged_many', 'I have judged five or more mock trial competitions in the past.'),
]


judged_rounds_choices = [
]

class Paradigm(models.Model):
    judge = models.OneToOneField('tourney.Judge', on_delete=models.CASCADE,
                                primary_key=True, related_name='paradigm')
    experience_years = models.DecimalField(default=0, max_digits=3, decimal_places=1, help_text='How many years of mock trial experience do you have?')
    experience_description = ArrayField(
        models.CharField(max_length=40, choices=experience_description_choices, null=True,
                         help_text='Do you have any experience competing or judging in high school, collegiate or law school mock trial competitions?',
                        blank=True),
        size=6, null=True, blank=True
    )
    affiliations = models.CharField(max_length=2000, null=True, blank=True)
    #scale On a scale of 1-10, I prefer mock trial attorneys who…
    comments = models.TextField(max_length=5000, null=True, blank=True)

    def __str__(self):
        return f"{self.judge}'s Paradigm"

role_choices = [
    ('att', 'Attorney'),
    ('wit', 'Witness')
]
class ParadigmPreference(models.Model):
    # tournament = models.ForeignKey('tourney.Tournament', on_delete=models.SET_NULL, related_name='paradigm_preferences',
    #                                related_query_name='paradigm_preference', null=True)
    role = models.CharField(max_length=40, choices=role_choices)
    low_end = models.CharField(max_length=40, null=True, blank=True)
    high_end = models.CharField(max_length=40, null=True, blank=True)

    def __str__(self):
        return f"{self.role.upper()}: {self.low_end} v. {self.high_end}"

class ParadigmPreferenceItem(models.Model):
    paradigm = models.ForeignKey(Paradigm, on_delete=models.CASCADE, related_name='preferences',
                                 related_query_name='preference_scale')
    paradigm_preference = models.ForeignKey(ParadigmPreference, on_delete=models.CASCADE, related_name='paradigm_preference_items',
                                   related_query_name='paradigm_preference_items', null=True)
    scale = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)],default=5)

submission/models/spirit.py
from django.db import models
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from tourney.models.team import Team
 
class Spirit(models.Model): 
    team = models.OneToOneField(Team, on_delete=models.CASCADE, primary_key=True,
                                related_name='spirit', default="")
    
    round1 = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(10)])
    
    round2 = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(10)])
    
    round3 = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(10)])
    # round4 = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(10)])
    
    q1 = models.TextField(max_length=5000, null=True, blank=True, help_text="Please list any reasons that you think one of the teams you competed against is especially deserving of the Spirit Award. Please provide a specific example, if possible.")
    
    q2 = models.TextField(max_length=5000, null=True, blank=True, help_text="Please list any team that you didn’t compete against but that you believe exhibited mock trial's ideals and, therefore, should receive additional consideration for the Spirit Award. Please provide a specific example.")
    submit = models.BooleanField(default=False, help_text='Submit')

    def get_score(self, round_num): 
        assert round_num in [1,2,3]
        if round_num == 1: 
            return self.round1
        elif round_num == 2:
            return self.round2
        elif round_num == 3:
            return self.round3
        # elif round_num == 4:
        #     return self.round4

    def __str__(self):
        return f"{self.team.__str__()} Spirit Form" 
    
    def clean(self):
        errors = []

        if errors != []:
            raise ValidationError(errors)

tourney/models/judge.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django_better_admin_arrayfield.models.fields import ArrayField

from tourney.models.team import Team
from tourney.models.tournament import Tournament


class Judge(models.Model):
    user = models.OneToOneField('accounts.User', on_delete=models.CASCADE,
                                primary_key=True, related_name='judge')
    conflicts = models.ManyToManyField(
        Team,
        blank=True
    )

    judge_friends = models.ManyToManyField(
        'self',
        blank=True
    )
    preside_choices = [
        (0, 'No'),
        (1, 'Yes'),
        (2, 'Can if needed'),
    ]

    preside = models.IntegerField(choices=preside_choices, default=0)
    available_round1 = models.BooleanField(default=False)
    available_round2 = models.BooleanField(default=False)
    available_round3 = models.BooleanField(default=False)
    available_round4 = models.BooleanField(default=False)
    available_round5 = models.BooleanField(default=False)

    checkin = models.BooleanField(default=False)

    def get_availability(self, round_num):
        return getattr(self, f"available_round{round_num}")

    def get_preside_preference(self):
        return self.preside_choices[self.preside][1]

    def is_assigned(self, round_num):
        assigned = False
        for round in self.rounds:
            if round.pairing.round_num == round_num:
                assigned = True
        return assigned


    @property
    def rounds(self):
        queryset = [round for round in self.presiding_rounds.all()] + [round for round in self.scoring_rounds.all()]\
                    +[round for round in self.extra_rounds.all()]
        return sorted(queryset, key=lambda x: x.pairing.round_num)

    @property
    def available_ballots(self):
        ballots = self.ballots.all()
        return [ballot for ballot in ballots if ballot.round.pairing.tournament == self.user.tournament ]

    def judged(self, round_num):
        p_judged = []
        d_judged = []
        for round in self.rounds:
            if round == None or round.p_team == None or round.d_team == None:
                continue
            if round.pairing.round_num != round_num:
                p_judged.append(Team.objects.get(pk=round.p_team.pk))
                d_judged.append(Team.objects.get(pk=round.d_team.pk))
        return p_judged, d_judged


    def __str__(self):
        return self.user.__str__()

templates/tourney/add_conflict.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load mytags %}

{% block content %}
{#	{% for team in form.conflicts %}#}
{#		{{ team }}<br>#}
{#	{% endfor %}#}

{##}
    <form method="post">
		{% csrf_token %}

		<div class="row">
            {% for value, label, team in form.conflicts.field.choices %}
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <li>
                    <label class="checkbox-label-container">
                        <input type="checkbox" value="{{ value }}" name="conflicts">
                        <span class="checkmark"></span>
												<strong>{{ team.team_name }}</strong>
												<span>({{ team.school }})</span></a><br/>
                    </label>
                </li>
            </div>
            {% endfor %}
        </div>
		<input class="button button-primary" type="submit" value="Save">
    </form>
{#	{{ field.field.instance. }}#}

{% endblock content %}

{% block js %}
	<script type="text/javascript" src="{% static 'js/form.js' %}"></script>
{% endblock js %}

templates/tourney/competitor_pronouns.html
{% extends "base.html" %}
{% load static %}

{% block content %}


<div class="container-fluid">
	{% for form in forms %}
		{% if form.errors %}
			{% for key, value in form.errors.items %}
				<div class="alert alert-danger" role="alert">{{ value }}</div>
			{% endfor %}
		{% endif %}
	{% endfor %}
	<h1>{{ team }} Members' Pronouns</h1>
	<form method="post">
		{% csrf_token %}
		{% for form in forms %}
			{% for field in form %}
				<div class="form-group col-md-12 p-1">
					<strong>{{ form.instance }}</strong>
					<br>
					{{ field }}
				</div>
			{% endfor %}
		{% endfor %}

		<br>
		<button class='button button-primary' type="submit">Save</button>
	</form>
</div>

{% endblock %}

templates/tourney/individual_awards.html
{% extends "base.html" %}
{% load static %}
{% load mytags %}

{% block content %}


	<div class="container-md">
		<table class="table table-striped table-bordered">
			<thead class="table-dark">
				<tr>
					<th scope="col"></th>
					<th colspan="4" scope="colgroup">Attorneys</th>
					<th colspan="4" scope="colgroup">Witnesses</th>
				</tr>
				<tr>
					<th scope="col">#</th>
					<th>Name</th>
					<th>Ranks</th>
					<th>Team</th>
					<th>Division</th>
					<th>Name</th>
					<th>Ranks</th>
					<th>Team</th>
					<th>Division</th>
				</tr>
			</thead>
			<tbody>
				{% for att, wit in atts_ranked|zip:atts_ranked %}
					<tr>
						<th scope="row">{{ forloop.counter }}</th>
						<td>{{ att }}</td>
						<td>{{ att.att_individual_score }}</td>
						<td>{{ att.team }}</td>
						<td>{{ att.team.division }}</td>
						<td>{{ wit }}</td>
						<td>{{ wit.wit_individual_score }}</td>
						<td>{{ wit.team }}</td>
						<td>{{ wit.team.division }}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>


{% endblock content %}

templates/tourney/judge_index.html
{% load static %}
{% load mytags %}
<div class="container-md">

	<div class="card my-5">
		<h4 class="card-header">Judge Profile</h4>
		<div class="card-body">
			<div class="card-group my-3">
				<div class="card border gx-2">
					<div class="card-header">
						Conflicted Teams
					</div>
					<div class="card-body text-start">
						<a href="{% url 'tourney:update_conflict' %}">
							<button type="button" class="button button-primary mb-2 py-1">Update Conflict</button>
						</a>
						<ul class="list-group mt-3">
							{% for team in request.user.judge.conflicts.all %}
								<li class="list-group-item">{{ team }}</li>
							{% endfor %}
						</ul>
					</div>
				</div>
				<div class="card border gx-2">
					<div class="card-header">
						Judge Friends
					</div>
					<div class="card-body text-start">
						<a href="{% url 'tourney:judge_friend' %}">
							<button type="button" class="button button-primary mb-2 py-1">Update Judge Friends</button>
						</a>
						<ul class="list-group mt-3">
							{% for friend in request.user.judge.judge_friends.all %}
								<li class="list-group-item">{{ friend }}</li>
							{% endfor %}
						</ul>
					</div>
				</div>

				<div class="card border gx-2">
					<div class="card-header">
						Preference
					</div>
					<div class="card-body text-start">
						<div class="my-2">
							<a class='button button-primary py-2' href="{% url 'submission:paradigm' request.user.username %}">
							Edit Paradigm
							</a>
						</div>
						<div class="mt-4">
							<a class='button button-primary py-2' href="{% url 'tourney:edit_preference'%}">
							Edit Availability
							</a>
						</div>
						<div class="card-text mt-3 mb-2">Can preside? {{ request.user.judge.get_preside_preference }}</div>
						<div class="card-text my-2">Availability:</div>
						<ul class="list-group">
							{% if request.user.judge.available_round1 %}
							<li class="list-group-item">Round 1</li>
							{% endif %}
							{% if request.user.judge.available_round2 %}
							<li class="list-group-item">Round 2</li>
							{% endif %}
							{% if request.user.judge.available_round3 %}
							<li class="list-group-item">Round 3</li>
							{% endif %}
							{% if request.user.judge.available_round4 %}
							<li class="list-group-item">Round 4</li>
							{% endif %}
							{% if request.user.judge.available_round5 %}
							<li class="list-group-item">Round 5</li>
							{% endif %}
						</ul>
					</div>
				</div>

				<div class="card border gx-2">
					<div class="card-header">
						Ballots
					</div>
					<div class="card-body text-start center">

						{% for ballot in request.user.judge.available_ballots %}
							{% if ballot.round.pairing.final_submit %}
								<div class="card-text mb-4">
									<a class="button button-primary py-2" href="{% url 'submission:ballot' ballot.pk|int_str %}">
										{{ ballot.round }}
									</a>
								</div>
							{% endif %}

						{% endfor %}

					</div>
				</div>
			</div>
		</div>
	</div>


</div>

templates/tourney/pairing.html
{% extends "base.html" %}
{% load static %}
{% load mytags %}

{% block content %}
	<h1>here is the pairing landing page</h1>
	{% if formset.errors %}
		{% for error in formset.errors %}
        <div class="alert alert-danger" role="alert">{{ error }}</div>
		{% endfor %}
    {% endif %}
	{% if formset.non_form_errors %}
		{% for error in formset.non_form_errors %}
        <div class="alert alert-danger" role="alert">{{ error }}</div>
		{% endfor %}
    {% endif %}

	<form method="post">
		{% csrf_token %}
		{{ formset.as_p }}
		<input class="button button-primary" type="submit" value="Save">
	</form>
{#	{{ div_1_teams.count}}#}
{#	{{ half_div_1_teams_num }}#}
{##}
{#	{{ div_2_teams.count}}#}
{#	{{ half_div_2_teams_num }}#}
{#	<div class="container-fluid">#}
{#		{{ div_1_teams.first.division }} Pairing#}
{#		<br>#}
{#		<form method="POST" action = "">{% csrf_token %}#}
{#			{% with ''|center:half_div_1_teams_num as range %}#}
{#				{% for _ in range %}#}
{#					Courtroom {{ forloop.counter0|chr }}#}
{#					<table>{{ form.as_table }}</table>#}
{##}
{#					<br>#}
{#				{% endfor %}#}
{#			{% endwith %}#}
{#			<input type="submit" value="Submit!"/>#}
{##}
{#        </form>#}

{#		{% for  in div_1_teams.count/2 %}#}
{##}
{##}
{#  		{% endfor %}#}
	</div>
{#	{{ div_2_teams.count}}#}
{#	{% for team in div_1_teams %}#}
{##}
{#	  	<strong> {{ team }} {{ team.school }}</strong><br>#}
{#  	{% endfor %}#}

{#	{% if div_2_teams == None %}#}
{#		{% for team in div_2_teams %}#}
{#			<strong> {{ team }} {{ team.school }}</strong><br>#}
{#		{% endfor %}#}
{#	{% endif %}#}

{% endblock content %}

templates/tourney/paradigm.html
{% extends "base.html" %}
{% load static %}

{% block content %}


<div class="container-fluid">
	{% for form in forms %}
		{% if form.errors %}
			{% for key, value in form.errors.items %}
				<div class="alert alert-danger" role="alert">{{ value }}</div>
			{% endfor %}
		{% endif %}
	{% endfor %}
	<h1>{{ judge }}'s Paradigm</h1>
	<form method="post">
		{% csrf_token %}
		{% for field in paradigm_form %}
			<div class="form-group col-md-12 p-1">
				{% if field.help_text %}
				<strong>{{ field.help_text }}</strong>
				{% else %}
				<strong>{{ field.label }}:</strong>
				{% endif %}
				<br>
				{{ field }}
			</div>
		{% endfor %}

		{% include "tourney/paradigm_preference.html" with combined_forms=forms %}
		<br>
		<button class='button button-primary' type="submit">Save</button>
	</form>
</div>

{% endblock %}

templates/tourney/team_index.html
{% load static %}
{% load mytags %}
<div class="container-md">




	<div class="card my-5">
		<h4 class="card-header">Team Profile</h4>
		<div class="card-body">
			<div class="card-group my-3">
				<div class="card border gx-2">
					<div class="card-header">
						Team Members
					</div>
					<div class="card-body text-start">
						<ul class="list-group">
						{% if user.team.competitors %}
							{% for competitor in user.team.competitors.all %}
								<li class="list-group-item">{{ competitor }}</li>
							{% endfor %}
						{% else %}
							You have no team members.
						{% endif %}
						</ul>

						<div class="row mt-3 mb-2 px-3">
							<a class="button button-primary"
								href="{% url 'tourney:view_individual_team' request.user.team.pk %}">
							Edit Team Info
							</a>
						</div>
						{% if user.tournament.spirit %}
							<div class="row mt-3 mb-2 px-3">
								<a class="button button-primary" href="{% url 'submission:spirit' request.user.team.pk %}">
									Spirit Award
								</a>
							</div>
						{% endif %}
{#						<ul class="list-group">#}
{#							<li class="list-group-item">{{ member }}</li>#}
{#						</ul>#}

					</div>
				</div>

				<div class="card border gx-2">
					<div class="card-header">
						Pairings
					</div>
					<div class="card-body text-start">
						{% if user.available_pairings %}
							{% for pairing in user.available_pairings %}
								<div class="card-text mb-4">
									<a class="button button-primary py-2" href="{% url 'tourney:view_pairing' pairing.pk %}">
										{{ pairing }}
									</a>
								</div>
							{% endfor %}
						{% else %}
							<div class="card-text">Pairings are not done yet. </div>
						{% endif %}
					</div>
				</div>

				<div class="card border gx-2">
					<div class="card-header">
						Captain Meeting Forms
					</div>
					<div class="card-body text-start">
						{% if not user.tournament.hide_captains_meeting %}
							{% if user.team.rounds %}
								{% for round in  user.team.rounds %}
									{% if round.pairing.team_submit %}
										<div class="card-text mb-4">
											<a class="button button-primary py-2" href="{% url 'submission:captains_meeting' round.captains_meeting.pk|int_str %}">
												{{ round }}
											</a>
										</div>
									{% endif %}
								{% endfor %}
							{% else %}
								<div class="card-text">You are not assigned to a round yet. </div>
							{% endif %}
						{% else %}
							<div class="card-text">Captain's Meeting forms are not digital for this tournament. </div>
						{% endif %}
					</div>
				</div>

				<div class="card border gx-2">
					<div class="card-header">
						Ballots
					</div>
					<div class="card-body text-start">
						{% if user.team.published_ballots %}
							{% for ballot in user.team.published_ballots %}
								<div class="card-text mb-4">
									<a class="button button-primary py-2" href="{% url 'submission:ballot' ballot.pk|int_str %}">
										{{ ballot }}
									</a>
								</div>
							{% endfor %}
						{% else %}
							<div class="card-text mb-4">No ballots have been published yet.</div>
						{% endif %}
					</div>
				</div>


			</div>
		</div>
	</div>





</div>