accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('judge_signup/', views.judge_signup, name='judge_signup'),
    path('team_signup/', views.team_signup, name='team_signup'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('tournament/switch', views.UserTournamentView.as_view(), name='edit_tournament'),
    path('tournament/create', views.create_tournament, name='create_tournament'),
    path('change_password/', views.ChangePassword.as_view(),
         name='change_password'),
    path('password_change_done/', views.DoneChangePassword.as_view(),
         name='password_change_done'),
]

submission/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'ballot'
urlpatterns = [
    path('ballot/<str:encrypted_pk>',
         views.BallotUpdateView.as_view(),
         name='ballot'),
    path('captains_meeting/<str:encrypted_pk>',
         views.CaptainsMeetingUpdateView.as_view(),
         name='captains_meeting'),

    path('paradigm/<str:judge>',
         views.edit_paradigm,
         name='paradigm'),
    
    path('spirit/<int:team_pk>', 
         views.edit_spirit, 
         name='spirit')
]

tabeasy/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include, path
from ajax_select import urls as ajax_select_urls

from tourney import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('accounts/', include('accounts.urls')),
    path('', include('tourney.urls')),
    path('submission/', include('submission.urls', namespace='submission')),
    path('generate_passwords', views.generate_passwords, name='generate_passwords'),
    path('load_teams', views.load_teams, name='load_teams'),
    path('load_judges', views.load_judges, name='load_judges'),
    path('load_teams_and_judges', views.load_teams_and_judges, name='load_teams_and_judges'),
    path('load_sections', views.load_sections, name='load_sections'),
    path('load_amta_witnesses', views.load_amta_witnesses),
    path('load_paradigms', views.load_paradigms),
    path('donate', views.donate, name='donate'),
    url(r'^ajax_select/', include(ajax_select_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tourney/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'tourney'
urlpatterns = [

    path('refresh', views.refresh, name='refresh'),
    path('edit_characters', views.edit_characters, name='edit_characters'),
    path('pairing', views.pairing_index, name='pairing_index'),
    path('pairing/<int:pk>', views.view_pairing, name='view_pairing'),
    path('pairing/edit/<int:round_num>', views.edit_pairing, name='edit_pairing'),
    path('pairing/delete/<int:round_num>', views.delete_pairing, name='delete_pairing'),
    path('pairing/next_pairing/<int:round_num>', views.next_pairing, name='next_pairing'),
    path('checkin_judges/<int:round_num>', views.checkin_judges, name='checkin_judges'),
    path('clear_checkin/', views.clear_checkin, name='clear_checkin'),
    path('checkin_all_judges/<int:round_num>', views.checkin_all_judges, name='checkin_all_judges'),
    path('view_ballot_status/<int:pairing_id>', views.view_ballot_status, name='view_ballot_status'),
    path('view_spirit_status', views.view_spirit_status, name='view_spirit_status'),
    path('add_spirit_forms', views.add_spirit_forms, name='add_spirit_forms'),
    path('tournament_setting', views.TournamentUpdateView.as_view(),  name='tournament_setting'),
    path('team', views.view_teams, name='view_teams'),
    path('team/<int:pk>', views.view_individual_team, name='view_individual_team'),
    path('team/delete/<int:pk>', views.delete_individual_team, name='delete_individual_team'),
    path('captains_meeting/<int:pairing_id>',
         views.view_captains_meeting_status, name='view_captains_meeting_status'),
    path('results', views.results, name='results'),
    path('individual_awards', views.individual_awards, name='individual_awards'),
    path('team/edit_competitor_pronouns/',
         views.edit_competitor_pronouns,
         name='edit_competitor_pronouns'),
    path('judge', views.view_judges, name='view_judges'),
    path('judge/delete/<int:pk>', views.delete_individual_judge, name='delete_individual_judge'),
    path('judge/<int:pk>', views.view_individual_judge, name='view_individual_judge'),
    path('judge/update_conflict',
         views.ConflictUpdateView.as_view(),
         name='update_conflict'),
    path('judge/judge_friends',
         views.JudgeFriendUpdateView.as_view(),
         name='judge_friend'),
    path('judge/judge_preference',
         views.JudgePreferenceUpdateView.as_view(),
         name='edit_preference'),
    

]

tourney/models/judge.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django_better_admin_arrayfield.models.fields import ArrayField

from tourney.models.team import Team
from tourney.models.tournament import Tournament


class Judge(models.Model):
    user = models.OneToOneField('accounts.User', on_delete=models.CASCADE,
                                primary_key=True, related_name='judge')
    conflicts = models.ManyToManyField(
        Team,
        blank=True
    )

    judge_friends = models.ManyToManyField(
        'self',
        blank=True
    )
    preside_choices = [
        (0, 'No'),
        (1, 'Yes'),
        (2, 'Can if needed'),
    ]

    preside = models.IntegerField(choices=preside_choices, default=0)
    available_round1 = models.BooleanField(default=False)
    available_round2 = models.BooleanField(default=False)
    available_round3 = models.BooleanField(default=False)
    available_round4 = models.BooleanField(default=False)
    available_round5 = models.BooleanField(default=False)

    checkin = models.BooleanField(default=False)

    def get_availability(self, round_num):
        return getattr(self, f"available_round{round_num}")

    def get_preside_preference(self):
        return self.preside_choices[self.preside][1]

    def is_assigned(self, round_num):
        assigned = False
        for round in self.rounds:
            if round.pairing.round_num == round_num:
                assigned = True
        return assigned


    @property
    def rounds(self):
        queryset = [round for round in self.presiding_rounds.all()] + [round for round in self.scoring_rounds.all()]\
                    +[round for round in self.extra_rounds.all()]
        return sorted(queryset, key=lambda x: x.pairing.round_num)

    @property
    def available_ballots(self):
        ballots = self.ballots.all()
        return [ballot for ballot in ballots if ballot.round.pairing.tournament == self.user.tournament ]

    def judged(self, round_num):
        p_judged = []
        d_judged = []
        for round in self.rounds:
            if round == None or round.p_team == None or round.d_team == None:
                continue
            if round.pairing.round_num != round_num:
                p_judged.append(Team.objects.get(pk=round.p_team.pk))
                d_judged.append(Team.objects.get(pk=round.d_team.pk))
        return p_judged, d_judged


    def __str__(self):
        return self.user.__str__()

tourney/views.py
import random
import re
import string
import openpyxl
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import ValidationError
from django.db import transaction
from django.forms import inlineformset_factory
from django.http import HttpResponseForbidden, HttpResponseNotFound, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import UpdateView
from tabeasy.settings import DEBUG
from django.core.files.storage import FileSystemStorage

from accounts.models import User
from submission.forms import CharacterPronounsForm
from submission.models.paradigm import Paradigm, ParadigmPreferenceItem, ParadigmPreference, \
    experience_description_choices
from submission.models.section import Section, SubSection
from submission.models.spirit import Spirit
from tabeasy.settings import DEBUG
from tabeasy.utils.mixins import JudgeOnlyMixin, PassRequestToFormViewMixin, TabOnlyMixin
from tabeasy_secrets.secret import str_int
from tourney.forms import RoundForm, UpdateConflictForm, UpdateJudgeFriendForm, PairingFormSet, PairingSubmitForm, \
    JudgeForm, CheckinJudgeForm, CompetitorPronounsForm, TournamentForm, CompetitorForm, TeamForm
from submission.models.ballot import Ballot
from submission.models.character import Character, CharacterPronouns
from tourney.models import Tournament
from tourney.models.judge import Judge
from tourney.models.round import Round, Pairing
from tourney.models.team import Team
from tourney.models.competitor import Competitor


def sort_teams(teams):
    return list(reversed(sorted(teams,
                                key=lambda x: (x.total_ballots, x.total_cs, x.total_pd))))


def index(request):
    return render(request, 'index.html')


@user_passes_test(lambda u: u.is_staff)
def results(request):
    tournament = request.user.tournament
    if tournament.split_division:
        div1_teams = sort_teams(
            [team for team in Team.objects.filter(division='Disney')])
        div2_teams = sort_teams(
            [team for team in Team.objects.filter(division='Universal')])
        dict = {'teams_ranked': [div1_teams, div2_teams]}
    else:
        teams = sort_teams(
            [team for team in Team.objects.filter(user__tournament=tournament)])
        dict = {'teams_ranked': teams}
    return render(request, 'tourney/tab/results.html', dict)


@user_passes_test(lambda u: u.is_staff)
def individual_awards(request):
    tournament = request.user.tournament
    competitor_scores = [(member, (member.p_att, member.d_att), (member.p_wit, member.d_wit))
                         for member in Competitor.objects.filter(team__user__tournament=tournament)]
    atts_ranked = [(member, 'P', att_score[0])
                   for member, att_score, wit_score in competitor_scores
                   if tournament.judges == 1 or att_score[0] >= 10] + \
                  [(member, 'D', att_score[1])
                   for member, att_score, wit_score in competitor_scores
                   if tournament.judges == 1 or att_score[1] >= 10]
    atts_ranked = sorted(atts_ranked, key=lambda x: -x[2])
    wits_ranked = [(member, 'P', wit_score[0])
                   for member, att_score, wit_score in competitor_scores
                   if tournament.judges == 1 or wit_score[0] >= 10] + \
                  [(member, 'D', wit_score[1])
                   for member, att_score, wit_score in competitor_scores
                   if tournament.judges == 1 or wit_score[1] >= 10]
    wits_ranked = sorted(wits_ranked, key=lambda x: -x[2])

    dict = {'ranked': zip(atts_ranked, wits_ranked)}
    return render(request, 'tourney/tab/individual_awards.html', dict)


@user_passes_test(lambda u: u.is_staff)
def next_pairing(request, round_num):
    tournament = request.user.tournament
    # if Pairing.objects.filter(tournament=tournament).exists():
    #     next_round = max([pairing.round_num for pairing in Pairing.objects.filter(tournament=tournament)])+1
    # else:
    #     next_round = 1
    next_round = round_num + 1
    if tournament.split_division:
        if next_round % 2 == 0:
            i_d_teams = sort_teams([team for team in Team.objects.filter(division='Disney')
                                    if team.next_side(next_round) == 'd'])
            div1_p_teams = sort_teams([team for team in Team.objects.filter(division='Disney')
                                       if team.next_side(next_round) == 'p'])
            div2_d_teams = sort_teams([team for team in Team.objects.filter(division='Universal')
                                       if team.next_side(next_round) == 'd'])
            div2_p_teams = sort_teams([team for team in Team.objects.filter(division='Universal')
                                       if team.next_side(next_round) == 'p'])
        else:
            div1_teams = sort_teams(
                [team for team in Team.objects.filter(division='Disney')])
            div1_p_teams = []
            div1_d_teams = []
            for i in range(0, len(div1_teams), 2):
                if random.randint(0, 1):
                    div1_p_teams.append(div1_teams[i])
                    div1_d_teams.append(div1_teams[i+1])
                else:
                    div1_p_teams.append(div1_teams[i+1])
                    div1_d_teams.append(div1_teams[i])
            div2_teams = sort_teams(
                [team for team in Team.objects.filter(division='Universal')])
            div2_p_teams = []
            div2_d_teams = []
            for i in range(0, len(div2_teams), 2):
                if random.randint(0, 1):
                    div2_p_teams.append(div2_teams[i])
                    div2_d_teams.append(div2_teams[i + 1])
                else:
                    div2_p_teams.append(div2_teams[i + 1])
                    div2_d_teams.append(div2_teams[i])

        dict = {'next_round': next_round,
                'divs': ['Disney', 'Universal'],
                'teams': [zip(div1_p_teams, div1_d_teams),
                          zip(div2_p_teams, div2_d_teams)]
                }
    else:
        if next_round % 2 == 0:
            d_teams = sort_teams([team for team in Team.objects.filter(user__tournament=tournament)
                                  if team.next_side(next_round) == 'd'])
            p_teams = sort_teams([team for team in Team.objects.filter(user__tournament=tournament)
                                  if team.next_side(next_round) == 'p'])
        else:
            teams = sort_teams(
                [team for team in Team.objects.filter(user__tournament=tournament)])
            p_teams = []
            d_teams = []
            for i in range(0, len(teams), 2):
                if random.randint(0, 1):
                    p_teams.append(teams[i])
                    d_teams.append(teams[i + 1])
                else:
                    p_teams.append(teams[i + 1])
                    d_teams.append(teams[i])
        dict = {'next_round': next_round,
                'divs': ['Teams'],
                'teams': [zip(p_teams, d_teams)]
                }
    return render(request, 'tourney/pairing/next_pairing.html', dict)


@user_passes_test(lambda u: u.is_staff)
def pairing_index(request):
    tournament = request.user.tournament
    round_num_lists = sorted(Pairing.objects.filter(
        tournament=tournament).values_list('round_num', flat=True).distinct())
    pairings = []
    for round_num in round_num_lists:
        pairings.append(Pairing.objects.filter(tournament=tournament,
                                               round_num=round_num).order_by('division'))
    if Pairing.objects.filter(tournament=tournament).exists():
        next_round = max([pairing.round_num for pairing in Pairing.objects.filter(
            tournament=tournament)]) + 1
    else:
        next_round = 1
    dict = {'pairings': pairings, 'next_round': next_round}
    if request.session.get('extra'):
        dict.update(request.session['extra'])
    return render(request, 'tourney/pairing/main.html', dict)


@user_passes_test(lambda u: u.is_staff)
def edit_pairing(request, round_num):
    tournament = request.user.tournament
    if DEBUG:
        RoundFormSet = inlineformset_factory(Pairing, Round, form=RoundForm, formset=PairingFormSet,
                                             max_num=int(tournament.division_team_num/2), validate_max=True,
                                             extra=int(tournament.division_team_num/2))
    else:
        RoundFormSet = inlineformset_factory(Pairing, Round, form=RoundForm, formset=PairingFormSet,
                                             max_num=int(tournament.division_team_num/2), validate_max=True,
                                             extra=int(tournament.division_team_num/2))

    if request.user.tournament.split_division:
        if not Pairing.objects.filter(round_num=round_num).exists():
            div1_pairing = Pairing.objects.create(
                round_num=round_num, division='Disney')
            div2_pairing = Pairing.objects.create(
                round_num=round_num, division='Universal')
        else:
            div1_pairing = Pairing.objects.filter(
                round_num=round_num).get(division='Disney')
            div2_pairing = Pairing.objects.filter(
                round_num=round_num).get(division='Universal')

        available_judges_pk = [judge.pk for judge in Judge.objects.all()
                               if judge.get_availability(div1_pairing.round_num)]
        judges = Judge.objects.filter(pk__in=available_judges_pk).order_by(
            '-checkin', '-preside', 'user__username').all()

        if request.method == "POST":
            div1_formset = RoundFormSet(request.POST, request.FILES, prefix='div1', instance=div1_pairing,

templates/tourney/tab/checkin_judges.html
{% extends 'base.html' %}

{% block content %}

		{% if form.errors %}
			{% for key, value in form.errors.items %}
				<div class="alert alert-danger" role="alert">{{ value }}</div>
			{% endfor %}
		{% endif %}

		<h2>Judge Checkin</h2>
		<form method="post">
			{% csrf_token %}
			{% include "utils/form_content.html" with form=form %}

			<button class='button button-primary' type="submit">Save</button>
		 	<input type="hidden" name="next" value="{{ next }}"/>
		</form>
		<br>
		<br>

		<div class="d-flex flex-row-reverse">
			<a href="{% url 'tourney:clear_checkin' %}">
			<button type="button" class="btn btn-outline-danger mx-2">Clear All Checkin</button>
			</a>
			<a href="{% url 'tourney:checkin_all_judges' round_num %}">
				<button type="button" class="btn btn-outline-darks mx-2">Check All In</button>
			</a>
		</div>

{% endblock content %}

templates/tourney/tab/tab_index.html
{% load static %}
{% load mytags %}

<div class="container-md">

	<div class="card my-5">
		<h4 class="card-header">Tab Profile</h4>
		<div class="card-body">
			<div class="card-group my-3">
				<div class="card border gx-2">
					<div class="card-header">
						Tournament

					</div>
					<div class="card-body text-start center mt-2">

						<div class="card-text mb-4">
							<a class="button button-primary py-2" href="{% url 'tourney:pairing_index' %}">
								Edit Pairings
							</a>
						</div>

						<div class="card-text mb-4">
							<a class="button button-primary py-2" href="{% url 'tourney:tournament_setting' %}">
								Tournament Settings
							</a>
						</div>

						<div class="card-text mb-4">
							<a class="button button-primary py-2" href="{% url 'tourney:edit_characters' %}">
								Characters
							</a>
						</div>

						<div class="card-text mb-4">
							<a class="button button-primary py-2" href="{% url 'tourney:view_teams' %}">
								Team List
							</a>
						</div>

						<div class="card-text mb-4">
							<a class="button button-primary py-2" href="{% url 'tourney:view_judges' %}">
								Judge List
							</a>
						</div>

					</div>
				</div>
				<div class="card border gx-2">
					<div class="card-header">
						Results
					</div>
					<div class="card-body text-start center mt-2">

						<div class="card-text mb-4">
							<a class="button button-primary py-2" href="{% url 'tourney:results' %}">
								Results
							</a>
						</div>

						<div class="card-text mb-4">
							<a class="button button-primary py-2" href="{% url 'tourney:individual_awards' %}">
								Individual Awards
							</a>
						</div>

						<div class="card-text mb-4">
							<a class="button button-primary py-2" href="{% url 'tourney:view_spirit_status' %}">
								Spirit Award
							</a>
						</div>


						<div class="card-text mb-4">
							<a class="button button-primary py-2" href="{% url 'tourney:refresh' %}">
								Refresh Results
							</a>
						</div>

					</div>
				</div>


				<div class="card border gx-2">
					<div class="card-header">
						Ballots
					</div>
					<div class="card-body text-start center mt-2">
							{% if user.available_pairings %}
								{% for pairing in user.available_pairings %}
									<div class="card-text mb-4">
										<a class="button button-primary py-2" href="{% url 'tourney:view_ballot_status' pairing.pk %}">
											{{ pairing }}
										</a>
									</div>
								{% endfor %}
							{% else %}
								<div class="card-text">Pairings are not done yet. </div>
							{% endif %}
					</div>
				</div>

				<div class="card border gx-2">
					<div class="card-header">
						Captains Meeting
					</div>
					<div class="card-body text-start center mt-2">
							{% if user.available_pairings %}
								{% for pairing in user.available_pairings %}
									<div class="card-text mb-4">
										<a class="button button-primary py-2" href="{% url 'tourney:view_captains_meeting_status' pairing.pk %}">
											{{ pairing }}
										</a>
									</div>
								{% endfor %}
							{% else %}
								<div class="card-text">Pairings are not done yet. </div>
							{% endif %}
					</div>
				</div>

			</div>
		</div>
	</div>



</div>

templates/tourney/tab/view_ballots_status.html
{% extends "base.html" %}
{% load static %}
{% load mytags %}

{% block content %}


	<div class="container-md">
		<table class="table table-striped table-bordered">
			<thead class="table-light">
				<tr>
					<th scope="col">Courtroom</th>
					<th scope="col">Judge Name</th>
					<th scope="col">P Team</th>
					<th scope="col">D Team</th>
					<th scope="col">P Score</th>
					<th scope="col">D Score</th>
					<th scope="col">P PD</th>
					<th scope="col">D PD</th>
					<th scope="col">Ballot</th>
					<th scope="col">Submitted?</th>
				</tr>
			</thead>
			<tbody>
				{% for ballot in ballots %}
					<tr>
						<th scope="row">{{ ballot.round.courtroom }}</th>
						<td>{{ ballot.judge }}</td>
						<td>{{ ballot.round.p_team }}</td>
						<td>{{ ballot.round.d_team }}</td>
						<td>{{ ballot.p_total_score }}</td>
						<td>{{ ballot.d_total_score }}</td>
						<td>{{ ballot.p_pd }}</td>
						<td>{{ ballot.d_pd }}</td>
						<td>
								<div class="m-2">
									<a class="button button-primary py-2" href="{% url 'submission:ballot' ballot.pk|int_str %}">
										View
									</a>
								</div>
						</td>
						<td>
							{% if ballot.submit %}
								<i class="fa-solid fa-check mx-1"></i>
							{% else %}
								<i class="fa-solid fa-xmark mx-1"></i>
							{% endif %}
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>


{% endblock content %}

templates/tourney/tab/view_captains_meeting_status.html
{% extends "base.html" %}
{% load static %}
{% load mytags %}

{% block content %}


	<div class="container-md">
		<table class="table table-striped table-bordered">
			<thead class="table-light">
				<tr>
					<th scope="col">Courtroom</th>
					<th scope="col">P Team</th>
					<th scope="col">D Team</th>
					<th scope="col">View</th>
					<th scope="col">Submitted?</th>
				</tr>
			</thead>
			<tbody>
				{% for captains_meeting in captains_meetings %}
					<tr>
						<th scope="row">{{ captains_meeting.round.courtroom }}</th>
						<td>{{ captains_meeting.round.p_team }}</td>
						<td>{{ captains_meeting.round.d_team }}</td>
						<td>
								<div class="m-2">
									<a class="button button-primary py-2" href="{% url 'submission:captains_meeting' captains_meeting.pk|int_str %}">
										View
									</a>
								</div>
						</td>
						<td>
							{% if captains_meeting.submit %}
								<i class="fa-solid fa-check mx-1"></i>
							{% else %}
								<i class="fa-solid fa-xmark mx-1"></i>
							{% endif %}
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>


{% endblock content %}

templates/tourney/tab/view_judges.html
{% extends "base.html" %}
{% load static %}
{% load mytags %}

{% block content %}


	<div class="container-md">
		<table class="table table-striped table-bordered">
			<thead class="table-light">
				<tr>
					<th scope="col">Judge Name</th>
					<th scope="col">Preside</th>
					<th colspan="4" scope="colgroup">Availability</th>
					<th scope="col">Conflicts</th>
					<th scope="col">Edit</th>
					<th scope="col">Delete</th>
				</tr>
				<tr>
					<th scope="col"></th>
					<th scope="col"></th>
					<th scope="col">Round 1</th>
					<th scope="col">Round 2</th>
					<th scope="col">Round 3</th>
					<th scope="col">Round 4</th>
					<th scope="col"></th>
					<th scope="col"></th>
					<th scope="col"></th>
				</tr>
			</thead>
			<tbody>
				{% for judge in judges %}
					<tr>
						<th scope="row">{{ judge }}</th>
						<td>
								{% if judge.preside == 2%}
									Can if needed
								{% elif judge.preside == 1 %}
									Yes
								{% else %}
									No
								{% endif %}
						</td>
						<td>
							{% if judge.available_round1 %}
								<i class="fa-solid fa-check mx-1"></i>
							{% else %}
								<i class="fa-solid fa-xmark mx-1"></i>
							{% endif %}
						</td>
						<td>
							{% if judge.available_round2 %}
								<i class="fa-solid fa-check mx-1"></i>
							{% else %}
								<i class="fa-solid fa-xmark mx-1"></i>
							{% endif %}
						</td>
						<td>
							{% if judge.available_round3 %}
								<i class="fa-solid fa-check mx-1"></i>
							{% else %}
								<i class="fa-solid fa-xmark mx-1"></i>
							{% endif %}
						</td>
						<td>
							{% if judge.available_round4 %}
								<i class="fa-solid fa-check mx-1"></i>
							{% else %}
								<i class="fa-solid fa-xmark mx-1"></i>
							{% endif %}
						</td>
						<td>
						{% if judge.conflicts.all %}
							{% for team in judge.conflicts.all %}
								{{ team }}{% if not forloop.last %},{% endif %}
							{% endfor %}
						{% else %}
							None
						{% endif %}
						</td>
						<td>
								<div class="m-2">
									<a class="button button-primary py-2" href="{% url 'tourney:view_individual_judge' judge.pk %}">
										Edit
									</a>
								</div>
						</td>
						<td>
								<div class="m-2">
									<a class="button button-primary py-2" href="{% url 'tourney:delete_individual_judge' judge.pk %}"
									onclick="return confirm('Are you sure you want to delete Judge {{ judge }}?');">
											Delete
									</a>
								</div>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
		<a href="{% url 'generate_passwords' %}">
			<button type="button" class="button button-primary m-2">
				Generate Passwords
			</button>
		</a>
		<a href="{% url 'load_teams_and_judges' %}">
			<button type="button" class="button button-primary m-2">
				Load Teams & Judges from Excel
			</button>
		</a>
		<a href="{% url 'accounts:judge_signup' %}">
			<button type="button" class="button button-primary m-2">
				Add Judge
			</button>
		</a>
	</div>



{% endblock content %}

templates/tourney/tab/view_teams.html
{% extends "base.html" %}
{% load static %}
{% load mytags %}

{% block content %}


	<div class="container-md">
		<table class="table table-striped table-bordered">
			<thead class="table-light">
				<tr>
					<th scope="col">Team Name</th>
					<th scope="col">School</th>
					<th scope="col">Roster</th>
					<th scope="col">Edit</th>
					<th scope="col">Delete</th>
				</tr>
			</thead>
			<tbody>
				{% for team in teams %}
					<tr>
						<th scope="row">{{ team }}</th>
						<td>{{ team.school }}</td>
						<td>
							{% for competitor in team.competitors.all %}
								{{ competitor }}{% if not forloop.last %},{% endif %}
							{% endfor %}
						</td>
						<td>
								<div class="m-2">
									<a class="button button-primary py-2" href="{% url 'tourney:view_individual_team' team.pk %}">
										Edit
									</a>
								</div>
						</td>
						<td>
								<div class="m-2">
									<a class="button button-primary py-2" href="{% url 'tourney:delete_individual_team' team.pk %}"
									onclick="return confirm('Are you sure you want to delete Team {{ team }}?');">
											Delete
									</a>
								</div>
						</td>

					</tr>
				{% endfor %}
			</tbody>
		</table>
		<a href="{% url 'generate_passwords' %}">
			<button type="button" class="button button-primary m-2">
				Generate Passwords
			</button>
		</a>
		<a href="{% url 'load_teams_and_judges' %}">
			<button type="button" class="button button-primary m-2">
				Load Teams & Judges from Excel
			</button>
		</a>
		<a href="{% url 'accounts:team_signup' %}">
			<button type="button" class="button button-primary m-2">
				Add Team
			</button>
		</a>
	</div>



{% endblock content %}