accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('judge_signup/', views.judge_signup, name='judge_signup'),
    path('team_signup/', views.team_signup, name='team_signup'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('tournament/switch', views.UserTournamentView.as_view(), name='edit_tournament'),
    path('tournament/create', views.create_tournament, name='create_tournament'),
    path('change_password/', views.ChangePassword.as_view(),
         name='change_password'),
    path('password_change_done/', views.DoneChangePassword.as_view(),
         name='password_change_done'),
]

tabeasy/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include, path
from ajax_select import urls as ajax_select_urls

from tourney import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('accounts/', include('accounts.urls')),
    path('', include('tourney.urls')),
    path('submission/', include('submission.urls', namespace='submission')),
    path('generate_passwords', views.generate_passwords, name='generate_passwords'),
    path('load_teams', views.load_teams, name='load_teams'),
    path('load_judges', views.load_judges, name='load_judges'),
    path('load_teams_and_judges', views.load_teams_and_judges, name='load_teams_and_judges'),
    path('load_sections', views.load_sections, name='load_sections'),
    path('load_amta_witnesses', views.load_amta_witnesses),
    path('load_paradigms', views.load_paradigms),
    path('donate', views.donate, name='donate'),
    url(r'^ajax_select/', include(ajax_select_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tourney/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'tourney'
urlpatterns = [

    path('refresh', views.refresh, name='refresh'),
    path('edit_characters', views.edit_characters, name='edit_characters'),
    path('pairing', views.pairing_index, name='pairing_index'),
    path('pairing/<int:pk>', views.view_pairing, name='view_pairing'),
    path('pairing/edit/<int:round_num>', views.edit_pairing, name='edit_pairing'),
    path('pairing/delete/<int:round_num>', views.delete_pairing, name='delete_pairing'),
    path('pairing/next_pairing/<int:round_num>', views.next_pairing, name='next_pairing'),
    path('checkin_judges/<int:round_num>', views.checkin_judges, name='checkin_judges'),
    path('clear_checkin/', views.clear_checkin, name='clear_checkin'),
    path('checkin_all_judges/<int:round_num>', views.checkin_all_judges, name='checkin_all_judges'),
    path('view_ballot_status/<int:pairing_id>', views.view_ballot_status, name='view_ballot_status'),
    path('view_spirit_status', views.view_spirit_status, name='view_spirit_status'),
    path('add_spirit_forms', views.add_spirit_forms, name='add_spirit_forms'),
    path('tournament_setting', views.TournamentUpdateView.as_view(),  name='tournament_setting'),
    path('team', views.view_teams, name='view_teams'),
    path('team/<int:pk>', views.view_individual_team, name='view_individual_team'),
    path('team/delete/<int:pk>', views.delete_individual_team, name='delete_individual_team'),
    path('captains_meeting/<int:pairing_id>',
         views.view_captains_meeting_status, name='view_captains_meeting_status'),
    path('results', views.results, name='results'),
    path('individual_awards', views.individual_awards, name='individual_awards'),
    path('team/edit_competitor_pronouns/',
         views.edit_competitor_pronouns,
         name='edit_competitor_pronouns'),
    path('judge', views.view_judges, name='view_judges'),
    path('judge/delete/<int:pk>', views.delete_individual_judge, name='delete_individual_judge'),
    path('judge/<int:pk>', views.view_individual_judge, name='view_individual_judge'),
    path('judge/update_conflict',
         views.ConflictUpdateView.as_view(),
         name='update_conflict'),
    path('judge/judge_friends',
         views.JudgeFriendUpdateView.as_view(),
         name='judge_friend'),
    path('judge/judge_preference',
         views.JudgePreferenceUpdateView.as_view(),
         name='edit_preference'),
    

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link async rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.8.1/css/all.css"
        integrity="sha384-Bx4pytHkyTDy3aJKjGkGoHPt3tvv6zlwwjc3iqN7ktaiEMLDPqLSZYts2OjKcBx1"
        crossorigin="anonymous">

  <!--jquery-->
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"
          integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
  <!-- Temporary Bootstrap reference -->
{#	dirty-form#}
	<script type="text/javascript" src="//cdn.jsdelivr.net/jquery.dirtyforms/2.0.0/jquery.dirtyforms.min.js"></script>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
				integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
          integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
					integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>


	<link rel="stylesheet" href="https://use.typekit.net/fiy6cyf.css">
  <link rel="stylesheet" href="{% static "styles/main.css" %}?v=0.1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'styles/mdb.min.css' %}"/>
	<link rel="shortcut icon" href="{% static "img/base/favicon.ico" %}"/>
	<title>{% block title %}Tabeasy{% endblock title %}</title>
	{% block css %}{% endblock css %}

</head>
<body>


<header class="full-width-bg-container" id="navbar-bg">
  <div class="card-container" id="navbar-container">
    <div class="main-content-container" id="main-navbar">

		<a class="navbar-brand navbar-link" target="_blank" href="{% url 'index' %}" id="header-title">
			<img src="{% static "img/base/logo.png" %}" alt='' width="40" height="38" class="ms-4 me-2 d-inline-block align-text-center">
			Tabeasy
		</a>

		{% if user.is_authenticated %}
			<a class="navbar-item button button-primary" id="menu-toggle"
				 href="javascript:void(0);" onclick="mobileMenuToggle()">
				<i class="far fa-bars"></i>
			</a>
			<div class="navbar-item dropdown" id="menu">
				<a class="button button-text-only dropdown-toggle" href="{% url "index" %}" role="button"
					 id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
					{{ user }}
				</a>

				<ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
					<li><a class="dropdown-item" href="{% url "index" %}">Profile</a></li>
{#					{% if user.is_superuser %}#}
{#						<li><a class="dropdown-item" href="{% url "admin:index" %}">Django Admin</a></li>#}
{#					{% endif %}#}
					{% if user.is_superuser %}
						<li><a class="dropdown-item" href="{% url "accounts:edit_tournament" %}">Select Tournament</a></li>
						<li><a class="dropdown-item" href="{% url "accounts:create_tournament" %}">Add Tournament</a></li>
					{% endif %}
					{% if user.is_team == False %}
						<li><a class="dropdown-item" href="{% url "accounts:change_password" %}">Change Password</a></li>
					{% endif %}
						<li><a class="dropdown-item" href="{% url "accounts:logout" %}">Logout</a></li>
				</ul>
			</div>

		{% else %}
			<a class="navbar-item button button-primary" id="menu-toggle"
				 href="javascript:void(0);" onclick="mobileMenuToggle()">
				<i class="far fa-bars"></i>
			</a>
			<div class="navbar-item" id="menu">
				<a class="button button-text-only" href="{% url "accounts:login" %}">Login</a>
				<a class="button button-text-only" href="{% url "accounts:signup" %}">Sign Up</a>
			</div>

		{% endif %}
    </div>
  </div>
</header>

 <div id="page-container">
  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}
  {% block content %}{% endblock content %}
</div>


<footer class="full-width-bg-container" id="footer-bg" >
	<div id="footer">
		<span id="copyright-info">Tabeasy &copy; 2022 by Carl Guo.</span>
		<span id="copyright-info">
			Tabeasy is made to be completely free of charge. If you enjoy using the website,
			please consider <a class="link-primary" href="{% url 'donate' %}">donating</a>.
		</span>

		<div id="footer-icon-container">
		  <a href="https://github.com/carlguo866/tabeasy" class="footer-icon"><i class="fab fa-github"></i></a>
		</div>
	</div>
</footer>
</body>

{% csrf_token %}


<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
<script src="https://kit.fontawesome.com/63d734a68c.js" crossorigin="anonymous"></script>
{% block js %}{% endblock js %}

</html>

templates/donate.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container-sm center">
	<div class="row">
		<div class="col-md-6">
			<h3 class="m-3">Venmo (in USD):</h3>
			<img src="{% static 'img/venmo.jpeg' %}" width="250px" class="m-3">
		</div>
		<div class="col-md-6">
			<h3 class="m-3">Wechat Pay (in RMB):</h3>
			<img src="{% static 'img/wechat_pay.jpeg' %}" width="250px"  class="m-3">
		</div>
	</div>

</div>


{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content%}

	{% for error in errors %}
		{{ error }}
	{% endfor %}
	{% if user.is_authenticated %}
		<h2>Welcome, {{ user }} for {{ user.tournament }}!</h2>
		{% if user.is_staff %}
			{% include 'tourney/tab/tab_index.html' %}
		{% endif %}

		{% if user.is_team%}
			{% include 'tourney/team_index.html' %}
		{% elif user.is_judge %}
			{% include 'tourney/judge_index.html' %}
		{% endif %}



	{% else %}
		{% include 'unauthenticated_index.html' %}
	{% endif %}

{% endblock content%}

templates/tab_index.html
You are a tab admin!<br>
Pairing page is here:<br>
<a href="{% url 'tourney:pairing_index' %}">
	<button type="button" class="button button-primary">Pairing</button>
</a>
<br>
Results page is here:<br>
<a href="{% url 'tourney:results' %}">
	<button type="button" class="button button-primary">Results</button>
</a>
<a href="{% url 'tourney:individual_awards' %}">
	<button type="button" class="button button-primary">Individual Awards</button>
</a>

templates/unauthenticated_index.html
{% load static %}

{% block css %}
  <link rel="stylesheet" type="text/css" href="{% static "styles/homepage.css" %}">
{% endblock %}

{% block content %}

		<div class="container-md center">
			<h1 class="mt-5">Tabeasy
				<img src="{% static "img/base/logo.png" %}" alt='' width="52.6" height="50" class="d-inline-block align-text-center">
				&mdash;</h1>
			<h2 class="mt-2s">Making Mock Trial Tournament Hosting Easy.</h2>

			<div class="homepage-row center my-4">
        <img src="{% static "img/homepage/downward_arrow.png" %}" id="chevron-down">
      </div>

			<div class="shadow-2-strong center my-4">
        <img src="{% static "img/homepage/homepage_demo.jpg" %}">
      </div>

			<div class="homepage-row center my-4">
        <img src="{% static "img/homepage/downward_arrow.png" %}" id="chevron-down">
      </div>

		</div>


    <div class="homepage-container my-4">
      <div class="homepage-row">
        <div class="homepage-section my-2">
          <h1>No More Manual Tabrooms</h1>
					<div class="description-container">
						Tabulating a tournament by hand is difficult, tedious, and error-prone. Tabeasy can change that.
					</div>
        </div>
       	<div class="homepage-section my-2">
          <h1>Free, Fast, Automated Tabulation System</h1>
					<div class="description-container">
						Pairing generation, ballot collection, &amp; award calculation, all within seconds.
					</div>
        </div>
      </div>
    </div>

		<div class="container-sm">
			<div class="card">
				<h3 class="card-header my-1">
					User Testimonials:
				</h3>
				<div class="card-group my-3">
					<div class="card gx-3">
{#						<img src="{% static 'img/homepage/iain_profile_pic.jpeg' %}" width="250" class="rounded mx-auto d-block">#}
						<div class="card-body">
							<div class="card-text mx-2" style="font-size: 17px;">
							"I’ve judged at two Tabeasy competitions, administrating the second,
								and I don’t see any need to use a different system. If you have a couple hours,
								an internet connection, and a love for this great activity, you owe it to your colleagues,
								students, and self to try Tabeasy."
							</div>
							<br>
							<div class="text-end" style="font-size: 17px;">
									&mdash; Iain Lampert, 2 times AMTA winner
							</div>
						</div>
					</div>
					<div class="card gx-3">
						<div class="card-body">
							<div class="card-text mx-2" style="font-size: 17px;">
								"I’m extremely grateful to Carl for developing Tabeasy — a superb mock trial tabulation tool.
								Using it for three tournaments, everything was smooth,
								and it certainly saved us a tremendous amount of time."
							</div>
							<br>
							<div class="text-end" style="font-size: 17px;">
									&mdash; Max Wang, Director of PPMT, Biggest Chinese MT Tournament
							</div>
						</div>
					</div>
					<div class="card gx-3">
						<div class="card-body">
							<div class="card-text mx-2" style="font-size: 17px;">
								I cannot speak more highly of Tabeasy.
								I’ve seen a lot of different tab softwares on the circuit, and this is the only one I’ve used that makes competitions easy for competitors, tab staff, and judges.
								The interface is extremely user friendly and makes it so much easier to monitor all aspects of hosting
								from start to finish.
							</div>
							<br>
							<div class="text-end" style="font-size: 17px;">
									&mdash; Riya Lakkaraju, All-American Attorney &amp; Witness
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="homepage-row center my-4">
			<img src="{% static "img/homepage/downward_arrow.png" %}" id="chevron-down">
		</div>

		<h1 class="center">Try it now!</h1>
		<div class="homepage-container my-4">
      <div class="homepage-row">
				<div class="homepage-section my-2">
					<div class="description-container">
						Tabeasy is made to be completely free of charge.
						If you plan to host a tournament on Tabeasy,
						please contact Carl Guo @ <a class="link-primary" href="mailto:carlguo@mit.edu">carlguo[at]mit[dot]edu</a>.
					</div>
        </div>
				<div class="homepage-section my-2">
          <div class="mb-4">
						&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; or &nbsp; &nbsp;
						<a class="button button-primary py-2" style="font-size:20px" href="{% url 'accounts:login' %}">
							Login
						</a>
					</div>
        </div>
      </div>
    </div>
		<br><br>


{% endblock content %}