tabeasy/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include, path
from ajax_select import urls as ajax_select_urls

from tourney import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('accounts/', include('accounts.urls')),
    path('', include('tourney.urls')),
    path('submission/', include('submission.urls', namespace='submission')),
    path('generate_passwords', views.generate_passwords, name='generate_passwords'),
    path('load_teams', views.load_teams, name='load_teams'),
    path('load_judges', views.load_judges, name='load_judges'),
    path('load_teams_and_judges', views.load_teams_and_judges, name='load_teams_and_judges'),
    path('load_sections', views.load_sections, name='load_sections'),
    path('load_amta_witnesses', views.load_amta_witnesses),
    path('load_paradigms', views.load_paradigms),
    path('donate', views.donate, name='donate'),
    url(r'^ajax_select/', include(ajax_select_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tourney/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'tourney'
urlpatterns = [

    path('refresh', views.refresh, name='refresh'),
    path('edit_characters', views.edit_characters, name='edit_characters'),
    path('pairing', views.pairing_index, name='pairing_index'),
    path('pairing/<int:pk>', views.view_pairing, name='view_pairing'),
    path('pairing/edit/<int:round_num>', views.edit_pairing, name='edit_pairing'),
    path('pairing/delete/<int:round_num>', views.delete_pairing, name='delete_pairing'),
    path('pairing/next_pairing/<int:round_num>', views.next_pairing, name='next_pairing'),
    path('checkin_judges/<int:round_num>', views.checkin_judges, name='checkin_judges'),
    path('clear_checkin/', views.clear_checkin, name='clear_checkin'),
    path('checkin_all_judges/<int:round_num>', views.checkin_all_judges, name='checkin_all_judges'),
    path('view_ballot_status/<int:pairing_id>', views.view_ballot_status, name='view_ballot_status'),
    path('view_spirit_status', views.view_spirit_status, name='view_spirit_status'),
    path('add_spirit_forms', views.add_spirit_forms, name='add_spirit_forms'),
    path('tournament_setting', views.TournamentUpdateView.as_view(),  name='tournament_setting'),
    path('team', views.view_teams, name='view_teams'),
    path('team/<int:pk>', views.view_individual_team, name='view_individual_team'),
    path('team/delete/<int:pk>', views.delete_individual_team, name='delete_individual_team'),
    path('captains_meeting/<int:pairing_id>',
         views.view_captains_meeting_status, name='view_captains_meeting_status'),
    path('results', views.results, name='results'),
    path('individual_awards', views.individual_awards, name='individual_awards'),
    path('team/edit_competitor_pronouns/',
         views.edit_competitor_pronouns,
         name='edit_competitor_pronouns'),
    path('judge', views.view_judges, name='view_judges'),
    path('judge/delete/<int:pk>', views.delete_individual_judge, name='delete_individual_judge'),
    path('judge/<int:pk>', views.view_individual_judge, name='view_individual_judge'),
    path('judge/update_conflict',
         views.ConflictUpdateView.as_view(),
         name='update_conflict'),
    path('judge/judge_friends',
         views.JudgeFriendUpdateView.as_view(),
         name='judge_friend'),
    path('judge/judge_preference',
         views.JudgePreferenceUpdateView.as_view(),
         name='edit_preference'),
    

]

tourney/models/competitor.py
from django.db import models
from tourney.models import Team

pronoun_choices = [
    ('he', 'he/him'),
    ('she', 'she/her'),
    ('they','they/them'),
    ('ze','ze/hir')
]

class Competitor(models.Model):
    name = models.CharField(max_length=60)
    team = models.ForeignKey(Team,on_delete=models.CASCADE,related_name='competitors',related_query_name='competitor')
    pronouns = models.CharField(max_length=20, choices=pronoun_choices, null=True, blank=True)
    p_att = models.IntegerField(default=0)
    d_att = models.IntegerField(default=0)
    p_wit = models.IntegerField(default=0)
    d_wit = models.IntegerField(default=0)


    def __str__(self):
        if self.pronouns == None:
            return self.name
        else:
            for (i, j) in pronoun_choices:
                if i == self.pronouns:
                    return f"{self.name} ({j})"

    def calc_att_individual_score(self):
        p_total = 0
        d_total = 0
        dict = {
            self.att_rank_1.all(): 5,
            self.att_rank_2.all(): 4,
            self.att_rank_3.all(): 3,
            self.att_rank_4.all(): 2,
        }
        for k, v in dict.items():
            for ballot in k:
                if (self.team.user.tournament.judges == 3) or \
                        (self.team.user.tournament.judges == 2 and ballot.judge != ballot.round.extra_judge) \
                        or (self.team.user.tournament.judges == 1 and ballot.judge == ballot.round.presiding_judge):
                    if ballot.round.p_team == self.team:
                        p_total += v
                    else:
                        d_total += v
        tournament = self.team.user.tournament
        if tournament.individual_award_rank_plus_record:
            p_total += self.team.p_ballots
            d_total += self.team.d_ballots
        self.p_att = p_total
        self.d_att = d_total

    def calc_wit_individual_score(self):
        p_total = 0
        d_total = 0
        dict = {
            self.wit_rank_1.all(): 5,
            self.wit_rank_2.all(): 4,
            self.wit_rank_3.all(): 3,
            self.wit_rank_4.all(): 2,
        }
        for k, v in dict.items():
            for ballot in k:
                if (self.team.user.tournament.judges == 3) or \
                        (self.team.user.tournament.judges == 2 and ballot.judge != ballot.round.extra_judge) \
                        or (self.team.user.tournament.judges == 1 and ballot.judge == ballot.round.presiding_judge):
                    if ballot.round.p_team == self.team:
                        p_total += v
                    else:
                        d_total += v
        tournament = self.team.user.tournament
        if tournament.individual_award_rank_plus_record:
            p_total += self.team.p_ballots
            d_total += self.team.d_ballots
        self.p_wit = p_total
        self.d_wit = d_total

    def __lt__(self, other):
        return self.id < other.id

    class Meta:
        ordering = ['id']

    def save(self, *args, **kwargs):
        self.calc_wit_individual_score()
        self.calc_att_individual_score()
        super().save(*args, **kwargs)

tourney/views.py
import random
import re
import string
import openpyxl
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import ValidationError
from django.db import transaction
from django.forms import inlineformset_factory
from django.http import HttpResponseForbidden, HttpResponseNotFound, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import UpdateView
from tabeasy.settings import DEBUG
from django.core.files.storage import FileSystemStorage

from accounts.models import User
from submission.forms import CharacterPronounsForm
from submission.models.paradigm import Paradigm, ParadigmPreferenceItem, ParadigmPreference, \
    experience_description_choices
from submission.models.section import Section, SubSection
from submission.models.spirit import Spirit
from tabeasy.settings import DEBUG
from tabeasy.utils.mixins import JudgeOnlyMixin, PassRequestToFormViewMixin, TabOnlyMixin
from tabeasy_secrets.secret import str_int
from tourney.forms import RoundForm, UpdateConflictForm, UpdateJudgeFriendForm, PairingFormSet, PairingSubmitForm, \
    JudgeForm, CheckinJudgeForm, CompetitorPronounsForm, TournamentForm, CompetitorForm, TeamForm
from submission.models.ballot import Ballot
from submission.models.character import Character, CharacterPronouns
from tourney.models import Tournament
from tourney.models.judge import Judge
from tourney.models.round import Round, Pairing
from tourney.models.team import Team
from tourney.models.competitor import Competitor


def sort_teams(teams):
    return list(reversed(sorted(teams,
                                key=lambda x: (x.total_ballots, x.total_cs, x.total_pd))))


def index(request):
    return render(request, 'index.html')


@user_passes_test(lambda u: u.is_staff)
def results(request):
    tournament = request.user.tournament
    if tournament.split_division:
        div1_teams = sort_teams(
            [team for team in Team.objects.filter(division='Disney')])
        div2_teams = sort_teams(
            [team for team in Team.objects.filter(division='Universal')])
        dict = {'teams_ranked': [div1_teams, div2_teams]}
    else:
        teams = sort_teams(
            [team for team in Team.objects.filter(user__tournament=tournament)])
        dict = {'teams_ranked': teams}
    return render(request, 'tourney/tab/results.html', dict)


@user_passes_test(lambda u: u.is_staff)
def individual_awards(request):
    tournament = request.user.tournament
    competitor_scores = [(member, (member.p_att, member.d_att), (member.p_wit, member.d_wit))
                         for member in Competitor.objects.filter(team__user__tournament=tournament)]
    atts_ranked = [(member, 'P', att_score[0])
                   for member, att_score, wit_score in competitor_scores
                   if tournament.judges == 1 or att_score[0] >= 10] + \
                  [(member, 'D', att_score[1])
                   for member, att_score, wit_score in competitor_scores
                   if tournament.judges == 1 or att_score[1] >= 10]
    atts_ranked = sorted(atts_ranked, key=lambda x: -x[2])
    wits_ranked = [(member, 'P', wit_score[0])
                   for member, att_score, wit_score in competitor_scores
                   if tournament.judges == 1 or wit_score[0] >= 10] + \
                  [(member, 'D', wit_score[1])
                   for member, att_score, wit_score in competitor_scores
                   if tournament.judges == 1 or wit_score[1] >= 10]
    wits_ranked = sorted(wits_ranked, key=lambda x: -x[2])

    dict = {'ranked': zip(atts_ranked, wits_ranked)}
    return render(request, 'tourney/tab/individual_awards.html', dict)


@user_passes_test(lambda u: u.is_staff)
def next_pairing(request, round_num):
    tournament = request.user.tournament
    # if Pairing.objects.filter(tournament=tournament).exists():
    #     next_round = max([pairing.round_num for pairing in Pairing.objects.filter(tournament=tournament)])+1
    # else:
    #     next_round = 1
    next_round = round_num + 1
    if tournament.split_division:
        if next_round % 2 == 0:
            i_d_teams = sort_teams([team for team in Team.objects.filter(division='Disney')
                                    if team.next_side(next_round) == 'd'])
            div1_p_teams = sort_teams([team for team in Team.objects.filter(division='Disney')
                                       if team.next_side(next_round) == 'p'])
            div2_d_teams = sort_teams([team for team in Team.objects.filter(division='Universal')
                                       if team.next_side(next_round) == 'd'])
            div2_p_teams = sort_teams([team for team in Team.objects.filter(division='Universal')
                                       if team.next_side(next_round) == 'p'])
        else:
            div1_teams = sort_teams(
                [team for team in Team.objects.filter(division='Disney')])
            div1_p_teams = []
            div1_d_teams = []
            for i in range(0, len(div1_teams), 2):
                if random.randint(0, 1):
                    div1_p_teams.append(div1_teams[i])
                    div1_d_teams.append(div1_teams[i+1])
                else:
                    div1_p_teams.append(div1_teams[i+1])
                    div1_d_teams.append(div1_teams[i])
            div2_teams = sort_teams(
                [team for team in Team.objects.filter(division='Universal')])
            div2_p_teams = []
            div2_d_teams = []
            for i in range(0, len(div2_teams), 2):
                if random.randint(0, 1):
                    div2_p_teams.append(div2_teams[i])
                    div2_d_teams.append(div2_teams[i + 1])
                else:
                    div2_p_teams.append(div2_teams[i + 1])
                    div2_d_teams.append(div2_teams[i])

        dict = {'next_round': next_round,
                'divs': ['Disney', 'Universal'],
                'teams': [zip(div1_p_teams, div1_d_teams),
                          zip(div2_p_teams, div2_d_teams)]
                }
    else:
        if next_round % 2 == 0:
            d_teams = sort_teams([team for team in Team.objects.filter(user__tournament=tournament)
                                  if team.next_side(next_round) == 'd'])
            p_teams = sort_teams([team for team in Team.objects.filter(user__tournament=tournament)
                                  if team.next_side(next_round) == 'p'])
        else:
            teams = sort_teams(
                [team for team in Team.objects.filter(user__tournament=tournament)])
            p_teams = []
            d_teams = []
            for i in range(0, len(teams), 2):
                if random.randint(0, 1):
                    p_teams.append(teams[i])
                    d_teams.append(teams[i + 1])
                else:
                    p_teams.append(teams[i + 1])
                    d_teams.append(teams[i])
        dict = {'next_round': next_round,
                'divs': ['Teams'],
                'teams': [zip(p_teams, d_teams)]
                }
    return render(request, 'tourney/pairing/next_pairing.html', dict)


@user_passes_test(lambda u: u.is_staff)
def pairing_index(request):
    tournament = request.user.tournament
    round_num_lists = sorted(Pairing.objects.filter(
        tournament=tournament).values_list('round_num', flat=True).distinct())
    pairings = []
    for round_num in round_num_lists:
        pairings.append(Pairing.objects.filter(tournament=tournament,
                                               round_num=round_num).order_by('division'))
    if Pairing.objects.filter(tournament=tournament).exists():
        next_round = max([pairing.round_num for pairing in Pairing.objects.filter(
            tournament=tournament)]) + 1
    else:
        next_round = 1
    dict = {'pairings': pairings, 'next_round': next_round}
    if request.session.get('extra'):
        dict.update(request.session['extra'])
    return render(request, 'tourney/pairing/main.html', dict)


@user_passes_test(lambda u: u.is_staff)
def edit_pairing(request, round_num):
    tournament = request.user.tournament
    if DEBUG:
        RoundFormSet = inlineformset_factory(Pairing, Round, form=RoundForm, formset=PairingFormSet,
                                             max_num=int(tournament.division_team_num/2), validate_max=True,
                                             extra=int(tournament.division_team_num/2))
    else:
        RoundFormSet = inlineformset_factory(Pairing, Round, form=RoundForm, formset=PairingFormSet,
                                             max_num=int(tournament.division_team_num/2), validate_max=True,
                                             extra=int(tournament.division_team_num/2))

    if request.user.tournament.split_division:
        if not Pairing.objects.filter(round_num=round_num).exists():
            div1_pairing = Pairing.objects.create(
                round_num=round_num, division='Disney')
            div2_pairing = Pairing.objects.create(
                round_num=round_num, division='Universal')
        else:
            div1_pairing = Pairing.objects.filter(
                round_num=round_num).get(division='Disney')
            div2_pairing = Pairing.objects.filter(
                round_num=round_num).get(division='Universal')

        available_judges_pk = [judge.pk for judge in Judge.objects.all()
                               if judge.get_availability(div1_pairing.round_num)]
        judges = Judge.objects.filter(pk__in=available_judges_pk).order_by(
            '-checkin', '-preside', 'user__username').all()

        if request.method == "POST":
            div1_formset = RoundFormSet(request.POST, request.FILES, prefix='div1', instance=div1_pairing,

templates/tourney/pairing/edit.html
{% extends "base.html" %}
{% load static %}
{% load mytags %}
{% load widget_tweaks %}


{% block content %}
{#	{% for formset in formsets %}#}
{#		adfnalkdnlk#}
{#		{{ formset.non_form_errors }}#}
{#	{% endfor %}#}

	<div class="container-md center">
			<h3>Edit Round {{ pairing.round_num }} Pairing</h3>
			{% for formset in formsets %}
				{% if formset.errors %}
					{% for formerror in formset.errors %}
						{% if formerror %}
							{% for key, value in formerror.items %}
								<div class="alert alert-danger" role="alert">{{ value }}</div>
							{% endfor %}
						{% endif %}
					{% endfor %}
				{% endif %}
				{% if formset.non_form_errors %}
{#					{% for key, value in formset.non_form_errors.items %}#}
{#						{% if value %}#}
							<div class="alert alert-danger" role="alert">{{ formset.non_form_errors }}</div>
{#						{% endif %}#}
{#					{% endfor %}#}
				{% endif %}
			{% endfor %}
	
			<form method="post">
				{% csrf_token %}

					{% for formset, submit_form in formsets|zip:submit_forms %}
						<div class="row gx-2 pb-2">
							<h4 class="mt-3">{{ formset.instance }}</h4>
							{{ formset.management_form }}
							<table class="table table-striped table-bordered">
								<thead class="table-light">
									<tr>
										<th scope="col">{{pairing.tournament.p_choice}} Team</th>
										<th scope="col">Defense Team</th>
										<th scope="col">Presiding Judge</th>
										<th scope="col">Scoring Judge</th>
										<th scope="col">Extra Judge</th>
									</tr>
								</thead>
								<tbody>
									{% for form in formset %}
										<tr>
										{{ form.media }}
{#											<td>{{ form.p_team }}</td>#}
{#											<td>{{ form.d_team }}</td>#}
											<td>{% render_field form.p_team class="form-select" name="p_team" %}</td>
											<td>{% render_field form.d_team class="form-select" name="d_team" %}</td>
											<td>{% render_field form.presiding_judge class="form-select" name="presiding_judge" %}</td>
											<td>{% render_field form.scoring_judge class="form-select" name="scoring_judge" %}</td>
											<td>{% render_field form.extra_judge class="form-select" name="scoring_judge" %}</td>
										</tr>
										{% for hidden in form.hidden_fields %}
												{{ hidden }}
										{% endfor %}
									{% endfor %}
								</tbody>
							</table>

							<div class="d-flex justify-content-center">
								<div class="form-check mx-3">
										<span class="form-check-label" style="padding-bottom: 20px"> Team Assignment Done?</span>
										{% render_field submit_form.team_submit class='form-check-input' name="submit" %}
								</div>
								<div class="form-check mx-3">
									<span class="form-check-label" style="padding-bottom: 20px"> Judge Assignment Done?</span>
									{% render_field submit_form.final_submit class='form-check-input' name="submit" %}
								</div>
								<div class="form-check mx-3">
									<span class="form-check-label" style="padding-bottom: 20px"> Publish Results (After Finishing Round)</span>
									{% render_field submit_form.publish class='form-check-input' name="submit" %}
								</div>
							</div>
						</div>
					{% endfor %}
				<input class="button btn-secondary" type="submit" value="Save"
						style="position:fixed; top: 100px; right: 20px">

			</form>
	<br>
	<br>
	</div>
	<div class="container-fluid">
			<div class="card">
				<h4 class="card-header">Judge List</h4>
				<div class="card-body">
					{% for judge in judges %}
						<div class="row">
							<div class="col-md-2">
									<ul class="list-group my-1">
										<li class="list-group-item">{{ judge }}</li>
									</ul>
							</div>
							<div class="col-md-3">
								<ul class="d-flex flex-wrap my-1">
									<li class="list-group-item border">Conflicts:</li>
									{% for conflict in judge.conflicts.all %}
										<li class="list-group-item border">{{ conflict }}</li>
									{% endfor %}
									{% for round in judge.rounds  %}
										<li class="list-group-item border border-info">{{ round.p_team }}</li>
										<li class="list-group-item border border-info">{{ round.d_team }}</li>
									{% endfor %}
								</ul>
							</div>
							<div class="col-md-3">
								<ul class="d-flex flex-wrap my-1">
									<li class="list-group-item border">Friends:</li>
									{% for friend in judge.judge_friends.all %}
										<li class="list-group-item border">{{ friend }}</li>
									{% endfor %}
								</ul>
							</div>
							<div class="col-md-1">
								<ul class="d-flex flex-wrap my-1">
									<li class="list-group-item border">Checkin:
									{% if judge.checkin %}
										<i class="fa-solid fa-check mx-1"></i>
									{% else %}
										<i class="fa-solid fa-xmark mx-1"></i>
									{% endif %}
									</li>
								</ul>
							</div>
							<div class="col-md-1">
								<ul class="d-flex flex-wrap my-1">
									<li class="list-group-item border">Preside:
										{% if judge.preside == 2%}
											CIN
										{% elif judge.preside == 1 %}
											Y
										{% else %}
											N
										{% endif %}
									</li>
								</ul>
							</div>
							<div class="col-md-1">
								<ul class="d-flex flex-wrap my-1">
									<li class="list-group-item border">Assigned:
										{% call_method judge 'is_assigned' pairing.round_num %}
									</li>
								</ul>
							</div>
						</div>
					{% endfor %}
				</div>
			</div>
	</div>
{% endblock content %}


{% block js %}
	<script type="text/javascript" src="{% static 'js/form.js' %}"></script>
{% endblock js %}

templates/tourney/pairing/main.html
{% extends "base.html" %}
{% load static %}
{% load mytags %}

{% block content %}
	<div class="container-md center">
		{% if errors %}
			{% for error in errors %}
				<div class="alert alert-danger" role="alert">
					{{ error }}
				</div>
			{% endfor %}
		{% endif %}

		<h1>Pairings</h1>
			{% for pairing in pairings %}
				<div class="m-4">
					<h3>Round {{ pairing.0.round_num }}</h3>
					{% for div_pairing in pairing %}
						<div class="row gx-2 pb-3">
							{% if pairing.division != None %}
								<h4>{{ div_pairing }}</h4>
							{% endif %}
							{% if div_pairing.rounds.exists %}
							<table class="table table-striped table-bordered table-responsive">
								<thead class="table-light">
									<tr>
										<th scope="col">Courtroom</th>
										<th scope="col">{{user.tournament.p_choice}} Team</th>
										<th scope="col">Defense Team</th>
										<th scope="col">Presiding Judge</th>
										<th scope="col">Scoring Judge</th>
										<th scope="col">Scoring Judge</th>
									</tr>
								</thead>
								<tbody>
									{% for round in div_pairing.get_rounds %}
										<tr>
											<th scope="row">{{ round.courtroom }}</th>
											<td>{{ round.p_team }}</td>
											<td>{{ round.d_team }}</td>
											<td>{{ round.presiding_judge }}</td>
											<td>{{ round.scoring_judge }}</td>
											<td>{{ round.extra_judge }}</td>
										</tr>
									{% endfor %}
								</tbody>
							</table>
							{% endif %}
						<div class="d-flex justify-content-center">
							<div class="div mx-2">
								All teams finalized?
								{% if div_pairing.team_submit %}
									<i class="fa-solid fa-check mx-1"></i>
								{% else %}
									<i class="fa-solid fa-xmark  mx-1"></i>
								{% endif %}
							</div>
							<div class="div mx-2">
								All judges finalized?
								{% if div_pairing.final_submit %}
									<i class="fa-solid fa-check mx-1"></i>
								{% else %}
									<i class="fa-solid fa-xmark mx-1"></i>
								{% endif %}
							</div>
							<div class="div mx-2">
								Results published after round ends?
								{% if div_pairing.publish %}
									<i class="fa-solid fa-check mx-1"></i>
								{% else %}
									<i class="fa-solid fa-xmark mx-1"></i>
								{% endif %}
							</div>
						</div>
						</div>
					{% endfor %}

				<div class="d-flex justify-content-center">
					<a href="{% url 'tourney:edit_pairing' pairing.0.round_num %}">
						<button type="button" class="button button-primary m-2">Edit Pairing {{ pairing.0.round_num }} Pairing</button>
					</a>
{#					<a href="{% url 'tourney:delete_pairing' pairing.0.round_num %}">#}
{#						<button type="button" class="button button-primary m-2">Delete Round {{ pairing.0.round_num }} Pairing</button>#}
{#					</a>#}
					<a href="{% url 'tourney:checkin_judges' pairing.0.round_num %}">
						<button type="button" class="button button-primary m-2" >Checkin Judges</button>
					</a>
					<a href="{% url 'tourney:delete_pairing' pairing.0.round_num %}">
						<button type="button" class="button button-primary m-2" onclick="return confirm('Are you sure you want to delete Pairing {{ pairing.0.round_num }}?');">Delete Pairing</button>
					</a>
					<a href="{% url 'tourney:next_pairing' pairing.0.round_num %}">
						<button type="button" class="button button-primary m-2">(Tentative) Next Pairing</button>
					</a>

				</div>
			</div>
			{% endfor %}

	<a href="{% url 'tourney:edit_pairing' next_round %}">
		<button type="button" class="button button-primary">Add Pairing</button>
	</a>


</div>

{% endblock content %}

templates/tourney/pairing/next_pairing.html
{% extends "base.html" %}
{% load static %}
{% load mytags %}


{% block content %}
<div class="container-md">
	<h2 class="pb-2">The next round is Round {{ next_round }}</h2>

	{% for div, div_pairing in divs|zip:teams %}
	<h3 class="pb-1">Division: {{ div }}</h3>
			<table class="table table-striped table-bordered">
				<thead class="table-dark">
					<tr>
						<th scope="col">{{ div }}</th>
						<th colspan="4" scope="colgroup">Prosecution</th>
						<th colspan="4" scope="colgroup">Defense</th>
					</tr>
					<tr>
						<th scope="col">Rank</th>
						<th>Name</th>
						<th>Ballots</th>
						<th>CS</th>
						<th>PD</th>
						<th>Name</th>
						<th>Ballots</th>
						<th>CS</th>
						<th>PD</th>
					</tr>
				</thead>
				<tbody>
					{% for p_team, d_team in div_pairing %}
						<tr>
							<th scope="row">{{ forloop.counter }}</th>
							<td>{{ p_team }}</td>
							<td>{{ p_team.total_ballots }}</td>
							<td>{{ p_team.total_cs }}</td>
							<td>{{ p_team.total_pd }}</td>
							<td>{{ d_team }}</td>
							<td>{{ d_team.total_ballots }}</td>
							<td>{{ d_team.total_cs }}</td>
							<td>{{ d_team.total_pd }}</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
			<br><br>
		{% endfor %}
</div>


{% endblock content %}

templates/tourney/pairing/view.html
{% extends "base.html" %}
{% load static %}
{% load mytags %}

{% block content %}
	<div class="container-md center">
		<h3>Round {{ pairing.0.round_num }} Pairing</h3>

		{% if pairing.0.team_submit %}
			{% for div_pairing in pairing %}
				<h3 class="row gx-2 pb-3">
					{% if pairing.division != None %}
						<h4>{{ div_pairing }}</h4>
					{% endif %}
					{% if div_pairing.rounds.exists %}
					<table class="table table-striped table-bordered table-responsive">
						<thead class="table-light">
							<tr>
								<th scope="col">Courtroom</th>
								<th scope="col">Prosecution Team</th>
								<th scope="col">Defense Team</th>
								{% if request.user.is_judge or request.user.is_staff  %}
									<th scope="col">Presiding Judge</th>
									<th scope="col">Scoring Judge</th>
									<th scope="col">Scoring Judge</th>
								{% endif %}
							</tr>
						</thead>
						<tbody>
							{% for round in div_pairing.get_rounds %}
								<tr>
									<th scope="row">{{ round.courtroom }}</th>
									<td>{{ round.p_team }}</td>
									<td>{{ round.d_team }}</td>
									{% if request.user.is_judge or request.user.is_staff  %}
										<td>{{ round.presiding_judge }}</td>
										<td>{{ round.scoring_judge }}</td>
										<td>{{ round.extra_judge }}</td>
									{% endif %}
								</tr>
							{% endfor %}
						</tbody>
					</table>
					{% endif %}

			{% endfor %}
		{% else %}
			<h3>Pairings are not done yet. </h3>
		{% endif %}

	</div>

{% endblock content %}